version: '3.7'

services:
  django_gunicorn:
    build:
      context: .
    volumes:
      - static:/static
    env_file:
      - .env
    ports:
      - "8002:8000"

  nginx:
    image: nginx:stable-alpine
    platform: linux/amd64
    volumes:
      - static:/static
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "81:80"
    depends_on:
      - django_gunicorn

  db:
    image: mysql:8.0
    platform: linux/amd64
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  static:
  mysql_data:
