app = 'sso-server'
primary_region = 'dfw'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'
  MYSQL_DATABASE = "sso_db"
  MYSQL_USER = "sso_user"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app', 'mysql']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048

[[mounts]]
  source = "mysqldata"
  destination = "/data"

[processes]
  app = "python manage.py runserver 0.0.0.0:8000"
  mysql = """mkdir -p /data/mysql && \
    mysql_install_db --datadir=/data/mysql --user=mysql && \
    mysqld --datadir=/data/mysql \
    --user=mysql \
    --init-file=/app/init.sql \
    --default-authentication-plugin=mysql_native_password"""

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'